### ISSUE TITLE
crashed when run it on the window10

### ISSUE THREAD

**Issue by ltg1710** [jinleili/simuverse#1]
run it on windows 10 by the compiler(rustc 1.67.0 (fc594f156 2023-01-24))
callstack is
``` 
thread 'main' panicked at 'called glDebugMessageCallback but it was not loaded.', C:\Users\xxx\.cargo\registry\src\github.com-1ecc6299db9ec823\glow-0.12.0\src\gl46.rs:4234:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library\core\src\panicking.rs:64
   2: glow::gl46::go_panic_because_fn_not_loaded
             at C:\Users\xxx\.cargo\registry\src\github.com-1ecc6299db9ec823\glow-0.12.0\src\gl46.rs:4234
   3: glow::gl46::call_atomic_ptr_2arg
             at C:\Users\xxx\.cargo\registry\src\github.com-1ecc6299db9ec823\glow-0.12.0\src\gl46.rs:4316
   4: glow::gl46::struct_commands::GlFns::DebugMessageCallback
             at C:\Users\xxx\.cargo\registry\src\github.com-1ecc6299db9ec823\glow-0.12.0\src\gl46.rs:10203
   5: glow::native::impl$2::debug_message_callback<void (*)(u32,u32,u32,u32,ref$<str$>)>
             at C:\Users\xxx\.cargo\registry\src\github.com-1ecc6299db9ec823\glow-0.12.0\src\native.rs:2545
   6: wgpu_hal::gles::egl::impl$12::enumerate_adapters
             at C:\Users\xxx\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-hal-0.15.2\src\gles\egl.rs:888
   7: wgpu_core::instance::impl$6::request_adapter::gather<wgpu_hal::gles::Api,tuple$<> >
             at C:\Users\litonggao\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.15.1\src\instance.rs:733
   8: wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::request_adapter<wgpu_core::hub::IdentityManagerFactory>
             at C:\Users\xxx\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.15.1\src\instance.rs:805
   9: wgpu::backend::direct::impl$7::instance_request_adapter
             at C:\Users\xxx\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.15.1\src\backend\direct.rs:576
  10: wgpu::context::impl$5::instance_request_adapter<wgpu::backend::direct::Context>
             at C:\Users\xxx\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.15.1\src\context.rs:1932
  11: wgpu::Instance::request_adapter
             at C:\Users\xxx\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.15.1\src\lib.rs:1424
  12: wgpu::util::init::initialize_adapter_from_env_or_default::async_fn$0
             at C:\Users\xxx\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.15.1\src\util\init.rs:79
  13: app_surface::request_device::async_fn$0
             at C:\Users\xxx\.cargo\git\checkouts\wgpu-in-app-358da915a14ea882\8271c28\app-surface\src\lib.rs:116
  14: app_surface::app_surface::impl$0::new::async_fn$0
             at C:\Users\xxx\.cargo\git\checkouts\wgpu-in-app-358da915a14ea882\8271c28\app-surface\src\app_surface.rs:24
  15: simuverse::framework::create_action_instance::async_fn$0<simuverse::SimuverseApp>
             at .\src\framework.rs:129
  16: pollster::block_on<enum2$<simuverse::framework::create_action_instance::async_fn_env$0<simuverse::SimuverseApp> > >
             at C:\Users\xxx\.cargo\registry\src\github.com-1ecc6299db9ec823\pollster-0.2.5\src\lib.rs:125
  17: simuverse::framework::run<simuverse::SimuverseApp>
             at .\src\framework.rs:31
  18: simuverse::main
             at .\src\main.rs:230
  19: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\core\src\ops\function.rs:507
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\simuverse.exe` (exit code: 101)
```

**Comment by jinleili** [comment]
与 wgpu 中的[此 issue](https://github.com/gfx-rs/wgpu/issues/2540) 有关，由于 wgpu 总是强制开启了 `gl` feature, 系统上只要安装比较新的 gl 驱动，就容易导致此 bug。

**Comment by ltg1710** [comment]
Now, it can be run perfectly on Windows 10. you are great!
